### PR TITLE
more documentation

### PR DESCRIPTION
**Pull request by Mav7**
Added Enumerable/Lazy, Enumerator, Fiber, Math, Object, ObjectSpace, Random, Struct, Time

### CODE REVIEW

**Comment by zzak** [comment]
@Mav7 I know you're doing good work on the documentation, but could you please let another party merge your pull requests?

It's good practice in OSS to use the pull request workflow and let someone else review and merge your changes.

Also, this patch is massive. Why is it so big :(

**Comment by Mav7** [comment]
@zzak So sorry I usually do but, this time, it wasn't a big change so I just went ahead. It won't happen again.

**Comment by Mav7** [comment]
@zzak As far as the size I don't know. When I ran ```mrbdoc``` to generate the docs a bunch of new docs were generated(the ones mentioned in the comment above). I think that might be why. Is that problem?

**Comment by zzak** [comment]
> it wasn't a big change so I just went ahead. It won't happen again.

But this is actually a really big change, there are over 50k additions and trying to tell what you actually added is impossible.

I don't mean to give you a hard time, but we should be more careful when committing these kinds of patches.

It looks like this change includes some template related output changes, perhaps this could have been committed separately.

What is the process for generating the docs? The README only mentions jekyll, so maybe this could be better documented as well.

**Comment by Mav7** [comment]
@zzak I meant big change as it I didn't write and actual documentation the way I usually do. What I usually do is I write yard documentation my of fork https://github.com/Mav7/mruby of mruby this documentation comes in the form of comments like this for example:
```Ruby
/**
 * Include a module in another class or module.
 * Equivalent to: 
 *
 *   module B                                                                                                         
 *     include A                                                                                                    
 *   end 
 * @param [mrb_state *] mrb_state* The current mruby state.
 * @param [struct RClass *] RClass* A reference to module or a class.
 * @param [struct RClass *] RClass* A reference to the module to be included.
 */
MRB_API void mrb_include_module(mrb_state*, struct RClass*, struct RClass*);
```
Then I have it be reviewed on there with a collaborator then I PR to mruby/mruby for review there before documenting it on my fork of this repo https://github.com/Mav7/mruby.github.io. I finally do a PR to mruby/mruby.github.io. The documentation is generated with a command ```mrbdoc``` using yard-mruby. This time I didn't write anything I just discovered a lot of new folders and files that were untracked. I didn't think it was unusual.

**Pull request merged**
